"""Central configuration: model registry, repo-local cache, backend selection.

All Hugging Face downloads are pinned to a repo-local cache directory so the
models live *inside the repository* (``./models``) rather than the user's global
``~/.cache``. The cache dir env vars are set at import time, before any
``transformers`` / ``huggingface_hub`` import, which is the only point at which
they take effect.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path

# --- Repo-local model cache ------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parent.parent
MODELS_DIR = Path(os.environ.get("TINYCOURT_MODELS_DIR", REPO_ROOT / "models"))
MODELS_DIR.mkdir(parents=True, exist_ok=True)

# Point every Hugging Face cache at the repo-local folder. Must happen before
# transformers / huggingface_hub are imported anywhere.
os.environ.setdefault("HF_HOME", str(MODELS_DIR))
os.environ.setdefault("HF_HUB_CACHE", str(MODELS_DIR / "hub"))
# Faster downloads via the Xet transfer backend (hf_transfer is deprecated and
# its env var only triggers a FutureWarning on every import).
os.environ.setdefault("HF_XET_HIGH_PERFORMANCE", "1")


# --- Model registry --------------------------------------------------------


@dataclass(frozen=True)
class ModelSpec:
    """A local model option, A/B-compared per docs/adr/0002."""

    key: str
    repo_id: str
    label: str
    # "bf16" (the small model) or "4bit" (the main model on an 8GB GPU).
    quantization: str
    approx_vram_gb: float
    # Only set for models that ship custom modeling code. The previous MiniCPM
    # defaults did — and their remote code crashes on transformers 5.x (see
    # docs/adr/0002 amendment), which is why the registry now defaults to Qwen3.
    trust_remote_code: bool = False


# Repo ids are overridable by env var so a wrong/renamed id never hard-blocks
# the build; the download script reports what it actually fetched.
MODEL_REGISTRY: dict[str, ModelSpec] = {
    # Qwen3-1.7B is a thinking-hybrid model; the local client disables thinking
    # via the chat template so it answers in the delimited format directly.
    "small": ModelSpec(
        key="small",
        repo_id=os.environ.get("TINYCOURT_MODEL_SMALL", "Qwen/Qwen3-1.7B"),
        label="Qwen3-1.7B (bf16, tiny)",
        quantization="bf16",
        approx_vram_gb=4.0,
    ),
    "main": ModelSpec(
        key="main",
        repo_id=os.environ.get("TINYCOURT_MODEL_MAIN", "Qwen/Qwen3-4B-Instruct-2507"),
        label="Qwen3-4B-Instruct-2507 (4-bit)",
        quantization="4bit",
        approx_vram_gb=3.5,
    ),
}

# Which local model the app loads by default (env-selectable, docs/adr/0002).
DEFAULT_MODEL_KEY = os.environ.get("TINYCOURT_MODEL", "main")

def _model_cached(spec: ModelSpec) -> bool:
    """True when the model's weights are already in the repo-local cache."""
    snapshots = MODELS_DIR / "hub" / ("models--" + spec.repo_id.replace("/", "--")) / "snapshots"
    if not snapshots.is_dir():
        return False
    return any((snap / "config.json").is_file() for snap in snapshots.iterdir())


def _default_backend() -> str:
    """Prefer the real local model whenever its weights are cached; fall back to
    the canned FakeClient only when nothing is downloaded yet. The trial must be
    LLM-generated by default — FakeClient is a bootstrap/test seam, not the show."""
    spec = MODEL_REGISTRY.get(DEFAULT_MODEL_KEY)
    return "local" if spec and _model_cached(spec) else "fake"


# Backend seam selector: "fake" (no GPU, canned text) or "local" (transformers).
# Env var wins; otherwise auto-selects "local" when the default model is cached.
BACKEND = os.environ.get("TINYCOURT_BACKEND") or _default_backend()


def selected_model() -> ModelSpec:
    return MODEL_REGISTRY[DEFAULT_MODEL_KEY]
